### ISSUE TITLE
Pipeline is currently failing due to lack of memory

### ISSUE THREAD

**Issue by kltm** [geneontology/sparql-for-pathway-go-cams#1]
```
16:52:40  org.openrdf.query.QueryEvaluationException: java.lang.OutOfMemoryError: Java heap space
16:52:40  	at com.bigdata.rdf.sail.Bigdata2Sesame2BindingSetIterator.hasNext(Bigdata2Sesame2BindingSetIterator.java:188)
16:52:40  	at info.aduna.iteration.IterationWrapper.hasNext(IterationWrapper.java:68)
16:52:40  	at org.openrdf.query.QueryResults.report(QueryResults.java:155)
[...]
16:52:40  	at scala.App.main$(App.scala:74)
16:52:40  	at org.renci.blazegraph.Main$.main(Main.scala:5)
16:52:40  	at org.renci.blazegraph.Main.main(Main.scala)
16:52:40  Caused by: java.lang.OutOfMemoryError: Java heap space
16:52:40  Makefile:20: recipe for target 'target/run_query' failed
16:52:40  make[1]: *** [target/run_query] Error 1
16:52:40  make[1]: Leaving directory '/var/lib/jenkins/workspace/logy_pipeline_snapshot-post-fail/sparql-for-pathway-go-cams'
16:52:40  Makefile:29: recipe for target 'target/metabolic_pthwy_gocams_count_mf_roots.tsv' failed
16:52:40  make: *** [target/metabolic_pthwy_gocams_count_mf_roots.tsv] Error 2
```

**Comment by kltm** [comment]
Got through step.
